server:
  port: 8082

management:
  endpoints:
    web:
      base-path: /actuator # Actuator 提供的 API 接口的根目录
      exposure:
        include: '*'  # 需要开放的端点
        exclude: # 需要排除的端点

#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/examsys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

spring:
  datasource:
    username: root
    password: bx20010208LSH!
    url: jdbc:mysql://139.9.58.231:3306/examsys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB

mybatis:
  type-aliases-package: edu.zstu.examsys.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true