// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElStep: typeof import('element-plus/es')['ElStep']
  const ElSteps: typeof import('element-plus/es')['ElSteps']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
}
export {}
