// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundFull: typeof import('./src/components/BackgroundFull.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Choice: typeof import('./src/components/QuestionEdit/Choice.vue')['default']
    ClickDropDown: typeof import('./src/components/ClickDropDown.vue')['default']
    Completion: typeof import('./src/components/QuestionEdit/Completion.vue')['default']
    DialogBox: typeof import('./src/components/DialogBox.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Exam: typeof import('./src/components/Exam.vue')['default']
    ExamCard: typeof import('./src/components/ExamCard.vue')['default']
    ExamCardAdd: typeof import('./src/components/ExamCardAdd.vue')['default']
    ExamEdit: typeof import('./src/components/ExamEdit.vue')['default']
    ExamTable: typeof import('./src/components/ExamTable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LoadingFull: typeof import('./src/components/LoadingFull.vue')['default']
    MultiChoice: typeof import('./src/components/QuestionEdit/MultiChoice.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    QuestionEdit: typeof import('./src/components/QuestionEdit/index.vue')['default']
    QuestionImport: typeof import('./src/components/QuestionImport.vue')['default']
    ReadOver: typeof import('./src/components/ReadOver.vue')['default']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    ShortAnswer: typeof import('./src/components/QuestionEdit/ShortAnswer.vue')['default']
    Svgicon: typeof import('./src/components/Svgicon/index.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TextEdit: typeof import('./src/components/TextEdit/index.vue')['default']
  }
}

export { }
